### ISSUE TITLE
Reunião #6 de 10/04/2021

### ISSUE THREAD

**Issue by Atsocs** [Atsocs/cobrITA#9]
## Todo na reunião
- [x] Foto da reunião, digam **xizzzz**
- [x] como cada um está indo / sentimento em relação a
  - [x] 7ª semana: :hot_face: ou :sunglasses: ?
  - [x] seu papel em relação ao projeto cobrITA?
- [x] marcar próxima reunião
- [x] **metas da semana**

## Comentários sobre CodeReview:
- [x] Pull Request (PR) #5 dos Sprites feita pelo @gbrlbrbs foi aceita! :rocket: :rocket: :rocket: Adorei como eu e ele conseguimos efetivamente usar o github em vez do whatsapp para se comunicar.
- [x] PR #7 dos powerups do @samuelv8 comentada, pedi algumas alterações antes de mergear
- [x] PR #5 e PR #6 relacionadas aos Snacks e ao Paused tiveram que ser misturadas devido a erro de uso do git por parte minha e do @skinnymega, cuidado!
  - [x] renomear branch Snacks

## Maiores explicações
- [x] geração do .json pelo [piskel](https://www.piskelapp.com/) @gbrlbrbs 
- [x] utilização do clock do GameControl para controlar a velocidade da cobra e os mapas, permitindo que rodemos a 60 fps @samuelv8

## Known Bugs (in master?)
- [x] bug cobra suicida com left-up mt rápido: não consegui reproduzir @skinnymega
- [x] bug popup tkinter @skinnymega (ver abaixo)

## Tarefas dessa semana
- [x] Preencher abaixo

## Git recommendations
- **Remember to ALWAYS use `git rebase master` in order to develop over the current accepted code**
  - [x] (show example on @samuelv8's branch)
- Please `git pull` and/or `git fetch` every time you open your IDE and before any push to this remote repository
- github issue system tips by @samuelv8 and @gbrlbrbs 
- `git cola`, `gitk --all` are useful tools and your best friends when working with `git`. While `gitk` comes with git, for `git-cola`, just `sudo apt-get install git-cola` for Ubuntu or download windows installer from [https://git-cola.github.io/](url)
  - [x] show branch tree in `gitk`
  - [x] exemplify functionality of `git-cola`
- Branch name and creation convention
  - Name should be in [`snake_case`](https://en.wikipedia.org/wiki/Snake_case) with name describing functionality implemented.
  - As a rule of thumb, create one branch per feature.
  - Anyone can create a pull request to any branch, not just to master.
- I strongly recommend using PyCharm and Linux, but feel free to choose the IDE and the OS you are most comfortable with :smiley: 

## Search for those topics, in case you don't know about them yet:
This is just a suggestion, not mandatory.
### Those where recommended to someone during CodeReview.
I'm making it easy concentrating the information here.
- [fstrings](https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/)
- useful [built-in functions](https://docs.python.org/3/library/functions.html), like:
  - [`map()`](https://docs.python.org/3/library/functions.html#map)
  - [`reversed()`](https://docs.python.org/3/library/functions.html#reversed)
  - [`issubclass()`](https://docs.python.org/3/library/functions.html#issubclass)
- [random](https://docs.python.org/dev/library/random.html) module:
  - [random.choices()](https://docs.python.org/dev/library/random.html#random.choices)
### Those are other personal suggestions of mine
- [pre-commit](https://calmcode.io/pre-commit/the-concept.html) and [black](https://calmcode.io/black/hooks.html)
- **[TDD](https://en.wikipedia.org/wiki/Test-driven_development)**
- [KISS](https://en.wikipedia.org/wiki/KISS_principle#In_software_development) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

**Comment by Atsocs** [comment]
Remember to use `git rebase master` in order to develop over the current accepted code

**Comment by Atsocs** [comment]
@gbrlbrbs explicar brevemente a geração do .json pelo [piskel](https://www.piskelapp.com/)

**Comment by Atsocs** [comment]
`git cola`, `gitk --all`

**Comment by Atsocs** [comment]
scores são números, conceitos são apresentados como snacks @samuelv8

**Comment by Atsocs** [comment]
[fstrings](https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/)

**Comment by Atsocs** [comment]
![image](https://user-images.githubusercontent.com/24798860/114259864-93037e80-99a7-11eb-9e49-1746d505be5f.png)
@skinnymega tá ciente desse bug?

**Comment by Atsocs** [comment]
## Tarefas da Semana, deadline ??/04/2021
- Mapas:
  - funcionalidade das camadas @Del-23
  - puxar squares acessíveis automaticamente
- Sons do jogo
  - comeu fruta
  - ganhou achievment
  - perdeu
  - selecionou opção
  - música de fundo
- Imagens estáticas
  - chapéu dos mágicos na tela de menu
- Páginas estáticas:
  - Help
  - Credits
- Achievments
  - deve salvar e carregar o estado atual de achievments de um arquivo
  - guardar também o highscore e estatísticas (por exemplo, quantas vezes jogou cada mapa, qual o tempo total gasto no cobrita, etc, seja criativo)

**Comment by Atsocs** [comment]
![WhatsApp Image 2021-04-10 at 09 35 13](https://user-images.githubusercontent.com/24798860/114281750-93872e00-9a16-11eb-9678-8338a4030a6e.jpeg)
